//! Cross-implementation correctness check between the Go `pkg/mpt` proof
//! producer and the Rust `proof_verify` consumer used by the SP1 guest.
//!
//! The fixture file is regenerated by:
//!     go test ./pkg/prover/ -run TestDumpProofFixtureForRust
//!
//! Binary format (all u32 little-endian):
//!   u32 root_len = 32, [u8; 32] root,
//!   u32 case_count,
//!   for each case:
//!     u32 key_len; key bytes,
//!     u8  has_value,
//!     [u32 value_len; value bytes]   (only when has_value == 1)
//!     u32 node_count,
//!     for each node: u32 node_len; node bytes.

use bsvm_proof_verify_test::verify_proof;

fn read_u32(buf: &[u8], at: &mut usize) -> u32 {
    let v = u32::from_le_bytes(buf[*at..*at + 4].try_into().unwrap());
    *at += 4;
    v
}

fn read_bytes<'a>(buf: &'a [u8], at: &mut usize) -> &'a [u8] {
    let len = read_u32(buf, at) as usize;
    let out = &buf[*at..*at + len];
    *at += len;
    out
}

#[test]
fn cross_check_against_go_mpt() {
    let path = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixture.bin");
    let bytes = match std::fs::read(&path) {
        Ok(b) => b,
        Err(_) => {
            // The Go test that generates this fixture has not been run.
            // Skip rather than fail — the host-side build pipeline runs
            // the dump test before this one in CI.
            eprintln!("fixture.bin missing; run `go test ./pkg/prover/ -run TestDumpProofFixtureForRust` to regenerate");
            return;
        }
    };

    let mut at = 0usize;
    let root_len = read_u32(&bytes, &mut at) as usize;
    assert_eq!(root_len, 32, "fixture root must be 32 bytes");
    let mut root = [0u8; 32];
    root.copy_from_slice(&bytes[at..at + 32]);
    at += 32;

    let case_count = read_u32(&bytes, &mut at) as usize;
    for i in 0..case_count {
        let key = read_bytes(&bytes, &mut at).to_vec();
        let has_value = bytes[at];
        at += 1;
        let expected_value = if has_value == 1 {
            Some(read_bytes(&bytes, &mut at).to_vec())
        } else {
            None
        };
        let node_count = read_u32(&bytes, &mut at) as usize;
        let mut proof: Vec<Vec<u8>> = Vec::with_capacity(node_count);
        for _ in 0..node_count {
            proof.push(read_bytes(&bytes, &mut at).to_vec());
        }

        let got = verify_proof(&root, &key, &proof)
            .unwrap_or_else(|e| panic!("case {}: verify_proof error: {:?}", i, e));
        assert_eq!(
            got, expected_value,
            "case {} key={:02x?}: value mismatch",
            i, key
        );
    }
}
