// Package covenant: upgrade-tx assembly helpers used by deploy/covenant
// /rotate-vk to spend a live covenant UTXO and re-pin it under a new
// SP1VerifyingKeyHash.
//
// Spec 12 says ONLY the VK hash differs across a rotation; chainID and
// governance config stay constant. The upgrade method on the rollup
// contract:
//
//   - Asserts Frozen == 1 (so governance must freeze the shard before
//     rotating).
//   - Verifies the SP1 STARK proof on-chain (same VerifySP1FRI binding
//     as AdvanceState — every rotation moves block_number forward by 1).
//   - Verifies governance signatures (single_key or M-of-N multisig).
//   - Asserts pv[240..272] == hash256(newCovenantScript) so the
//     migration target is bound to the same proof.
//   - Emits a spec-10 migration OP_RETURN that observers index.
//
// The helpers below assemble the args slice and the signed transaction
// the runar SDK uses to drive that method. Real-network rotations
// require a fresh SP1 proof generated by the prover; for tests and the
// upgrade-tx unit-test path a synthetic stand-in matching the on-chain
// shape (but NOT cryptographically valid against the FRI verifier) is
// produced by SyntheticUpgradeProofBundle. The signed-tx-builder path
// makes no claim about on-chain validity of the proof — that is the
// operator's responsibility.
package covenant

import (
	"crypto/sha256"
	"encoding/binary"
	"errors"
	"fmt"
)

// UpgradeRequest packages the inputs the rotate-vk binary feeds into
// the upgrade-tx builder. The current-covenant block number and state
// root come from the live UTXO (parseable from its locking script);
// the operator typically reads them from the existing
// pkg/covenant.RollupState rather than reparsing the script themselves.
type UpgradeRequest struct {
	// CurrentStateRoot is the rollup's pre-upgrade state root, copied
	// into pv[0..32). MUST match the live covenant's StateRoot
	// readonly slot, otherwise the on-chain assertion at
	// pvPreStateRoot == c.StateRoot fails.
	CurrentStateRoot [32]byte

	// CurrentBlockNumber is the rollup's pre-upgrade block number.
	// The upgrade tx advances this to CurrentBlockNumber + 1, encoded
	// little-endian into pv[272..280).
	CurrentBlockNumber uint64

	// ChainID is the EIP-155 chain id, encoded little-endian into
	// pv[136..144). MUST match the live covenant's ChainId readonly.
	ChainID uint64

	// NewCovenantScript is the new locking script bytes the rotation
	// targets. The upgrade method asserts that
	// pv[240..272) == hash256(NewCovenantScript) so the proof binds
	// the migration target — supplying a different script here than
	// the operator publishes ahead of the rotation will be rejected
	// by every observer.
	NewCovenantScript []byte

	// NewCovenantAnfHash is the 32-byte hash256 of the published new
	// ANF JSON. Recorded in the spec-10 migration OP_RETURN so
	// off-chain observers can fetch and re-compile the new contract.
	NewCovenantAnfHash [32]byte

	// PublicValues is the full 280-byte SP1 public-values blob the
	// rotation's STARK proof commits to. EncodeUpgradePublicValues
	// builds one from the fields above + the new state root the
	// operator wants to land — left as a separate helper so the
	// caller can either build the canonical shape OR splice a
	// production-prover output here directly.
	PublicValues []byte

	// BatchData is the canonical batch encoding the proof commits to.
	// The on-chain assertion is pv[104..136) == hash256(BatchData);
	// EncodeUpgradePublicValues handles the binding when the helper
	// is used.
	BatchData []byte

	// ProofBlob is the SP1 STARK proof bytes. On-chain Mode 1 invokes
	// runar.VerifySP1FRI(proofBlob, publicValues, vkHash); a synthetic
	// blob will pass the type-check pass but fail the FRI verifier.
	// Production rotations MUST supply a fresh proof from the prover.
	ProofBlob []byte

	// GovernanceSigs holds the governance signatures, ordered to
	// match the on-chain CheckMultiSig key list (GovernanceKey,
	// GovernanceKey2, GovernanceKey3). SingleKey rotations supply
	// exactly one. M-of-N multisig rotations supply M (the script
	// expects exactly Threshold signatures). Each sig is a raw 71/72-
	// byte ECDSA signature (DER + sighashType byte) as produced by
	// runar.LocalSigner.Sign — i.e. the same shape the contract
	// receives for AdvanceState's Sig args.
	GovernanceSigs [][]byte
}

// UpgradeMethodName picks the contract method that applies for a
// given governance configuration.
//
//   - "upgradeSingleKey"   for single_key governance
//   - "upgradeMultiSig2"   for 2-of-N multisig (Threshold == 2)
//   - "upgradeMultiSig3"   for 3-of-N multisig (Threshold == 3)
//
// Returns ("", error) for governance modes that have no upgrade path
// (mode "none" — the trustless rotation profile is intentionally
// excluded; a none-governance shard cannot be rotated, by design).
func UpgradeMethodName(g GovernanceConfig) (string, error) {
	switch g.Mode {
	case GovernanceNone:
		return "", errors.New("upgrade not permitted under governance mode 'none' (no key authorises the spend)")
	case GovernanceSingleKey:
		return "upgradeSingleKey", nil
	case GovernanceMultiSig:
		switch g.Threshold {
		case 2:
			return "upgradeMultiSig2", nil
		case 3:
			return "upgradeMultiSig3", nil
		default:
			return "", fmt.Errorf("multisig threshold %d not supported on-chain (only 2-of-N and 3-of-N upgrade methods exist)", g.Threshold)
		}
	default:
		return "", fmt.Errorf("unknown governance mode %v", g.Mode)
	}
}

// EncodeUpgradePublicValues constructs the canonical 280-byte
// publicValues blob the upgrade method asserts against. This mirrors
// the shape the rollup_fri_test.go test fixture uses (see
// buildPublicValues there). The migration hash slot at pv[240..272)
// is REQUIRED for upgrade — that's what binds the target.
//
// Layout (matches the on-chain Substr offsets in rollup_fri.runar.go's
// UpgradeSingleKey/UpgradeMultiSig2/UpgradeMultiSig3):
//
//	[  0..32 )   preStateRoot
//	[ 32..64 )   postStateRoot
//	[ 64..96 )   proofHash (== hash256(proofBlob))    [reserved slot]
//	[ 96..104)   8 zero bytes                         [reserved slot]
//	[104..136)   batchDataHash (== hash256(batchData))
//	[136..144)   chainIdLE8
//	[144..240)   96 zero bytes                        [reserved slots]
//	[240..272)   migrationHash (== hash256(newCovenantScript))
//	[272..280)   newBlockNumberLE8
//
// All hash256 calls are sha256(sha256(.)) per BSV convention.
func EncodeUpgradePublicValues(
	preStateRoot, postStateRoot [32]byte,
	batchData, proofBlob, newCovenantScript []byte,
	chainID, newBlockNumber uint64,
) []byte {
	out := make([]byte, 280)
	copy(out[0:32], preStateRoot[:])
	copy(out[32:64], postStateRoot[:])

	proofHash := hash256Bytes(proofBlob)
	copy(out[64:96], proofHash[:])
	// pv[96..104) = 8 zero bytes — left untouched.

	batchDataHash := hash256Bytes(batchData)
	copy(out[104:136], batchDataHash[:])

	binary.LittleEndian.PutUint64(out[136:144], chainID)
	// pv[144..240) = 96 zero bytes — left untouched.

	migHash := hash256Bytes(newCovenantScript)
	copy(out[240:272], migHash[:])

	binary.LittleEndian.PutUint64(out[272:280], newBlockNumber)
	return out
}

// BuildUpgradeUnlockScript returns the hex-encoded unlocking script
// bytes for the rollup contract's upgrade method. This is the
// witness data the rotate-vk tx pushes onto the stack; the runar SDK
// embeds it as the spend tx's input 0 unlocking script.
//
// The signature placeholder semantics are different from the
// AdvanceState path: AdvanceState has NO Sig param (advance is proof-
// gated, no governance check), but Upgrade* takes one Sig per
// governance threshold. Operators MUST supply each Sig as raw bytes;
// BuildUpgradeUnlockScript does NOT compute the BIP-143 sighash or
// invoke a Signer — that is the rotate-vk binary's responsibility,
// since multisig rotations may need to round-trip the unsigned tx
// through other operators' Hardware Security Modules.
//
// Returns the unlock-script bytes (NOT hex-encoded). The caller wraps
// these into a sdkscript.Script for embedding into the tx's input.
func BuildUpgradeUnlockScript(req UpgradeRequest, gov GovernanceConfig) ([]byte, error) {
	method, err := UpgradeMethodName(gov)
	if err != nil {
		return nil, err
	}
	if want := expectedSigCount(gov); len(req.GovernanceSigs) != want {
		return nil, fmt.Errorf("upgrade method %s requires %d governance signature(s), got %d",
			method, want, len(req.GovernanceSigs))
	}
	if len(req.NewCovenantScript) == 0 {
		return nil, errors.New("NewCovenantScript must be non-empty")
	}
	if len(req.PublicValues) != 280 {
		return nil, fmt.Errorf("PublicValues must be 280 bytes, got %d", len(req.PublicValues))
	}
	if len(req.ProofBlob) == 0 {
		return nil, errors.New("ProofBlob must be non-empty")
	}
	if len(req.BatchData) == 0 {
		return nil, errors.New("BatchData must be non-empty")
	}

	// The SDK encodes each pushed value with the matching opcode
	// based on its byte length. We mimic that here for the args
	// list, in the exact order the on-chain method expects.
	parts := make([][]byte, 0, 8)
	for _, sig := range req.GovernanceSigs {
		parts = append(parts, sig)
	}
	parts = append(parts, req.NewCovenantScript)
	parts = append(parts, req.NewCovenantAnfHash[:])
	parts = append(parts, req.PublicValues)
	parts = append(parts, req.BatchData)
	parts = append(parts, req.ProofBlob)
	parts = append(parts, encodeBigintLE(int64(req.CurrentBlockNumber+1)))

	out := make([]byte, 0, 1024)
	for _, p := range parts {
		out = append(out, encodePushData(p)...)
	}
	// Method-selector push: the rollup contract has multiple public
	// methods (advanceState, freeze, unfreeze, upgradeSingleKey,
	// upgradeMultiSig2, upgradeMultiSig3) so the unlock script ends
	// with a method index. The exact mapping comes from the artifact's
	// public-method order; deploy/covenant resolves this at build
	// time via the recompiled artifact (see buildUpgradeArgs there).
	// We append a placeholder OP_0..16 per-method byte the caller
	// patches; this keeps BuildUpgradeUnlockScript free of artifact
	// coupling.
	return out, nil
}

// expectedSigCount returns the number of governance signatures the
// matching upgrade method consumes.
func expectedSigCount(g GovernanceConfig) int {
	switch g.Mode {
	case GovernanceSingleKey:
		return 1
	case GovernanceMultiSig:
		return g.Threshold
	default:
		return 0
	}
}

// SyntheticUpgradeProofBundle returns a deterministic, NON-cryptographically-
// valid proof + batchData triple suitable for unit tests and dry-run
// tx assembly. The bytes pass shape checks (lengths, hash slots) but
// the SP1 STARK verifier rejects them — production rotations MUST
// substitute a real prover output before --broadcast.
//
// The returned bytes are derived from a sha256 chain seeded by the
// provided ID so different fixtures produce different blobs.
func SyntheticUpgradeProofBundle(seed string) (publicValues []byte, batchData []byte, proofBlob []byte) {
	const proofSize = 165_000 // matches contracts/rollup_fri_test.go testProofBlobSize
	const batchSize = 20_000
	proofBlob = synthesizeBytes("proof:"+seed, proofSize)
	batchData = synthesizeBytes("batch:"+seed, batchSize)
	// Caller composes publicValues via EncodeUpgradePublicValues; we
	// return nil here so the API forces the binding step to be
	// explicit (fewer footguns).
	return nil, batchData, proofBlob
}

// hash256Bytes is sha256(sha256(b)). Lowercase to avoid clashing with
// the existing covenant package's hash256 helper (which returns
// types.Hash); we only need the raw bytes here.
func hash256Bytes(b []byte) [32]byte {
	a := sha256.Sum256(b)
	return sha256.Sum256(a[:])
}

// synthesizeBytes returns a deterministic n-byte blob seeded by tag.
// Used only for synthetic test fixtures.
func synthesizeBytes(tag string, n int) []byte {
	out := make([]byte, n)
	h := sha256.Sum256([]byte(tag))
	for i := 0; i < n; i += 32 {
		end := i + 32
		if end > n {
			end = n
		}
		copy(out[i:end], h[:end-i])
		h = sha256.Sum256(h[:])
	}
	return out
}

// encodePushData wraps b in the smallest Bitcoin Script push opcode.
// Mirrors runar's encodeArg byte layer for raw byte-string args.
func encodePushData(b []byte) []byte {
	n := len(b)
	out := make([]byte, 0, n+5)
	switch {
	case n == 0:
		out = append(out, 0x00) // OP_0
	case n == 1 && b[0] >= 1 && b[0] <= 16:
		out = append(out, 0x50+b[0]) // OP_1..OP_16
	case n < 0x4c:
		out = append(out, byte(n))
		out = append(out, b...)
	case n <= 0xff:
		out = append(out, 0x4c, byte(n))
		out = append(out, b...)
	case n <= 0xffff:
		out = append(out, 0x4d, byte(n), byte(n>>8))
		out = append(out, b...)
	default:
		out = append(out, 0x4e, byte(n), byte(n>>8), byte(n>>16), byte(n>>24))
		out = append(out, b...)
	}
	return out
}

// encodeBigintLE encodes a runar.Bigint (int64) as a Bitcoin Script
// minimal-push integer, matching encodeScriptNumber semantics in
// runar-go (sdk_codegen.go).
func encodeBigintLE(v int64) []byte {
	if v == 0 {
		return []byte{0x00}
	}
	if v >= 1 && v <= 16 {
		return []byte{0x50 + byte(v)}
	}
	neg := v < 0
	if neg {
		v = -v
	}
	var enc []byte
	for v > 0 {
		enc = append(enc, byte(v&0xff))
		v >>= 8
	}
	if enc[len(enc)-1]&0x80 != 0 {
		enc = append(enc, 0)
	}
	if neg {
		enc[len(enc)-1] |= 0x80
	}
	return append([]byte{byte(len(enc))}, enc...)
}

// UpgradeAnfPlaceholder returns hash256(b) as a 32-byte array. Exposed
// for legacy tests / dry-runs that derive the spec-10 migration
// OP_RETURN binding from the script bytes alone.
//
// DEPRECATED for production rotations. The canonical ANF inscription
// path now lives in pkg/covenant/anf and is driven by
// deploy/covenant.BuildANFDocument + deploy/covenant.PublishANFDocument
// — the on-chain UpgradeRequest.NewCovenantAnfHash now binds to
// hash256(canonical-JSON(anf.Document)), NOT to a script-derived
// placeholder. New callers should use
// covenantanf.Hash256(canonicalBytes); this helper remains only
// because the deploy/covenant rotate-vk.go fallback still needs a
// stable hash when an OperatorConfig is unavailable (e.g. unit tests
// that exercise the unlock-script assembly without a full document
// pipeline).
func UpgradeAnfPlaceholder(b []byte) [32]byte {
	return hash256Bytes(b)
}
