# BSVM devnet for {{PROJECT_NAME}}
#
# Generated by `npx create-bsvm-devnet`. Mirrors the shape of the
# upstream bsv-evm/docker-compose.yml but pinned to a single proving
# mode and chain ID for this scaffold.

networks:
  bsvm-{{PROJECT_NAME}}:
    name: bsvm-{{PROJECT_NAME}}
    driver: bridge

x-bsvm-common: &bsvm-common
  image: bsvm:devnet
  restart: unless-stopped
  networks:
    - bsvm-{{PROJECT_NAME}}
  environment: &bsvm-env
    BSVM_PROVE_MODE: ${BSVM_PROVE_MODE:-{{PROVE_MODE}}}
    BSVM_CHAIN_ID: "{{CHAIN_ID}}"
    BSVM_BSV_RPC: "http://devuser:devpass@bsv-regtest:18332"
    BSVM_BSV_NETWORK: "regtest"
    BSVM_EXPLORER: "true"
    BSVM_LOG_LEVEL: info
    BSVM_GENESIS_DIR: /shared/genesis
    BSVM_BATCH_SIZE: "16"
    BSVM_FLUSH_DELAY: "1s"
    BSVM_DEPOSIT_CONFIRMATIONS: "1"

services:
  bsv-regtest:
    image: bitcoinsv/bitcoin-sv:latest
    networks:
      - bsvm-{{PROJECT_NAME}}
    command: >
      bitcoind
        -regtest
        -server
        -rpcuser=devuser
        -rpcpassword=devpass
        -rpcallowip=0.0.0.0/0
        -rpcbind=0.0.0.0
        -port=18444
        -rpcport=18332
        -txindex=1
        -excessiveblocksize=4000000000
        -maxstackmemoryusageconsensus=0
    ports:
      - "18332:18332"
    volumes:
      - bsv-data:/root/.bitcoin
    healthcheck:
      test: >
        bitcoin-cli -regtest -rpcuser=devuser -rpcpassword=devpass
        getblockchaininfo
      interval: 3s
      timeout: 2s
      retries: 20

  bsv-miner:
    image: bitcoinsv/bitcoin-sv:latest
    networks:
      - bsvm-{{PROJECT_NAME}}
    depends_on:
      bsv-regtest:
        condition: service_healthy
    entrypoint: /bin/sh
    command: >
      -c '
        ADDR=$$(bitcoin-cli -regtest -rpcconnect=bsv-regtest
          -rpcuser=devuser -rpcpassword=devpass getnewaddress)
        while true; do
          bitcoin-cli -regtest -rpcconnect=bsv-regtest
            -rpcuser=devuser -rpcpassword=devpass
            generatetoaddress 1 $$ADDR > /dev/null 2>&1
          sleep 10
        done
      '

  bsvm-init:
    image: bsvm:devnet
    networks:
      - bsvm-{{PROJECT_NAME}}
    depends_on:
      bsv-regtest:
        condition: service_healthy
    environment:
      BSVM_PROVE_MODE: {{PROVE_MODE}}
      BSVM_CHAIN_ID: "{{CHAIN_ID}}"
      BSVM_BSV_RPC: "http://devuser:devpass@bsv-regtest:18332"
    entrypoint: /bin/sh
    command: >
      -c '
        bsv-evm dev mine --blocks 150
        bsv-evm init \
          --chain-id {{CHAIN_ID}} \
          --prove-mode {{PROVE_MODE}} \
          --governance single_key \
          --gas-price 1 \
          --prefund-accounts hardhat \
          --output /shared/genesis
      '
    volumes:
      - shared-genesis:/shared/genesis

  node1:
    <<: *bsvm-common
    environment:
      <<: *bsvm-env
      BSVM_NODE_NAME: node1
      BSVM_RPC_PORT: "8545"
      BSVM_P2P_PORT: "9945"
      BSVM_ROLE: prover
      BSVM_COINBASE: "0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266"
      BSVM_PEERS: "{{NODE2_PEERS}}"
    ports:
      - "8545:8545"
      - "9945:9945"
    volumes:
      - shared-genesis:/shared/genesis:ro
      - node1-data:/data/bsvm
    depends_on:
      bsvm-init:
        condition: service_completed_successfully

{{EXTRA_NODES}}

volumes:
  bsv-data:
  shared-genesis:
  node1-data:
{{EXTRA_VOLUMES}}
