{
  "name": "{{PROJECT_NAME}}",
  "version": "0.1.0",
  "private": true,
  "description": "BSVM devnet scaffold generated by create-bsvm-devnet.",
  "scripts": {
    "up": "docker compose up",
    "up:detached": "docker compose up -d",
    "down": "docker compose down",
    "reset": "docker compose down -v",
    "logs": "docker compose logs -f",
    "compile": "hardhat compile",
    "deploy": "hardhat run scripts/deploy.ts --network devnet",
    "status": "hardhat bsvm:status --network devnet"
  },
  "devDependencies": {
    "@nomicfoundation/hardhat-toolbox": "^5.0.0",
    "hardhat": "^2.22.0",
    "hardhat-bsvm": "^0.1.0",
    "ethers": "^6.13.0",
    "typescript": "^5.4.0",
    "ts-node": "^10.9.2",
    "@types/node": "^20.11.0"
  }
}
