# {{PROJECT_NAME}}

A BSVM devnet scaffold generated by
[`create-bsvm-devnet`](https://www.npmjs.com/package/create-bsvm-devnet).

## Quickstart

```bash
# 1. Install Node deps
npm install

# 2. Bring up the devnet (BSV regtest + BSVM nodes)
npm run up

# 3. In another terminal, compile and deploy the sample contract
npm run compile
npm run deploy
```

## What you get

- Chain ID: `{{CHAIN_ID}}`
- Proving mode: `{{PROVE_MODE}}`
- Nodes: {{NODE_COUNT}} ({{NODE_DESCRIPTION}})
- Default RPC URL: `http://localhost:8545`
- Pre-funded Hardhat default test accounts (1000 wBSV each)

## Useful commands

```bash
npm run up           # start devnet (foreground)
npm run up:detached  # start devnet (background)
npm run down         # stop
npm run reset        # stop and wipe state
npm run logs         # tail node + bsv-regtest logs
npm run status       # proving status from node 1
```

The Hardhat config in `hardhat.config.ts` registers `devnet` (and any
additional nodes) using the `hardhat-bsvm` plugin, so all standard
Hardhat workflows (`hardhat test`, `hardhat run`, `hardhat console`)
work against the devnet out of the box.
